### ISSUE TITLE
Should prevent creating VM with name longer than 15 characters

### ISSUE THREAD

**Issue by axelgMS** [Azure/azure-sdk-for-ruby#1012]
Looks like Ruby SDK allows creating VM with a name longer than 15 characters. This should not be allowed.
Portal prevents this, and PowerShell too. eg:

$vmName = "TestResourceNameXYZ-TestDataDisk-TestResourceNames-ABCDEF-123456"

PS C:\> New-AzureRmVM -ResourceGroupName $resourceGroup -Location $location -VM $vmConfig
WARNING: Since the VM is created using premium storage, existing standard storage account, axelgsa47167195, is used for boot diagnostics.
**New-AzureRmVM : Windows computer name cannot be more than 15 characters long, be entirely numeric, or contain the following characters: ` ~ ! @ # $ % ^ & * ( ) = + _ [ ] { } \ | ; : . ' " , < > / ?.**
ErrorCode: InvalidParameter
ErrorMessage: Windows computer name cannot be more than 15 characters long, be entirely numeric, or contain the following characters: ` ~ ! @ # $ % ^ & * ( ) = + _ [ ] { } \ | ; : . ' " , < > / ?.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 3ea56e6d-b0e2-4d18-98f9-6488bebd9903
At line:1 char:1
+ New-AzureRmVM -ResourceGroupName $resourceGroup -Location $location - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.NewAzureVMCommand

**Comment by veronicagg** [comment]
thanks for reporting, we'll investigate and get back on this.

**Comment by sarangan12** [comment]
@axelgMS Adding such constraints on the SDK depends on the entries in swagger. I have done necessary changes to Ruby SDK to handle the constraints if they are available. But, only the compute team could add such constraints to the swagger and I have created an issue https://github.com/Azure/azure-rest-api-specs/issues/1990 for the compute team. 

Since there is no pending action items, I will be closing this issue
