### ISSUE TITLE
Initializing clients needs tenet_id, client_id, client_secret and subscription_id to be passed in

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1092]
Either in options or in env variables, we need the credentials for clients to work. 
More details to be added from customer scenario.

**Comment by veronicagg** [comment]
@stuartpreston FYI

**Comment by sarangan12** [comment]
Message from Stuart Preston:

**Specifically, even though we sent in credentials (tenant_id, client_id, and client_secret) via the ApplicationTokenProvider in code, this credentials object appears to be reset by the time the client initializes.  We were able to create a client successfully but only when setting environment variables with tenant, client_id and secret, and passing an empty options hash to the client.

I suspect there's something missing about our understanding of the difference between Azure::ARM::Configurable and Azure::ARM::Default or the logic that passes through the configurable items so that they don't reset**

**Comment by sarangan12** [comment]
The issue has been verified and confirmed. The Azure::ARM::Default always tries to create credentials from the environment variables which is incorrect. With the latest release 0,15.1, this issue has been fixed.
