### ISSUE TITLE
Ruby job for new RPs in azure-rest-api-specs repo fails

### ISSUE THREAD

**Issue by veronicagg** [Azure/azure-sdk-for-ruby#1648]
When a new Resource Provider is created in the azure-rest-api-specs repo, SDK generation jobs for Ruby fail because our Rakefile tries to find a gem folder that doesn't exist. 
Case 1:
INFO:swaggertosdk.autorest_tools:running: bundle exec ruby /tmp/tmp2df4xvw9/sdk/generators/requirefilegen/src/require_file_generator.rb --mode=rollup --sdk_path=/tmp/tmp2df4xvw9/sdk --gem_name=azure_sdk
INFO:swaggertosdk.autorest_tools:rake aborted!
INFO:swaggertosdk.autorest_tools:Errno::ENOENT: No such file or directory @ dir_s_chdir - /tmp/tmp2df4xvw9/sdk/management/azure_mgmt_stor_simple1200_series/lib/profiles.
 The readme section for Ruby was added by the author in the PR they are submitting -  https://github.com/Azure/azure-rest-api-specs/pull/3718

Case 2:
Command: bundle install && rake arm:regen_all_profiles['azure_mgmt_databox']
Finished with return code 10
and output:
Could not locate Gemfile

We should probably modify our Rakefile process to run what's needed based on the folders existing in the repo and not on an external list which may not be equivalent.

**Comment by anuchandy** [comment]
For case 2: the PR is https://github.com/Azure/azure-rest-api-specs/pull/3885

If we go to CI https://travis-ci.org/Azure/azure-rest-api-specs/builds/429648122?utm_source=github_status&utm_medium=notification it is showing "azure-sdk-for-java" generation failed and in detailed view https://travis-ci.org/Azure/azure-rest-api-specs/jobs/429648131#L687 we can see that failure is due to `bundle install && rake arm:regen_all_profiles['azure_mgmt_databox']` which has nothing to do with Java.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
