### ISSUE TITLE
Azure::BaseManagement::Location is colliding with Location active record model

### ISSUE THREAD

**Issue by mledom** [Azure/azure-sdk-for-ruby#250]
I created a sample app that show this issue: https://github.com/mledom/azure_test

I have not required the gem either, only added the gem to the bundle.

**Comment by devigned** [comment]
Is this what you were seeing?

```bash
$ rake test
rake aborted!
TypeError: superclass mismatch for class Location
```

**Comment by devigned** [comment]
I see. Well, it's not so much that the gem pollutes the global namespace, it's that the Rails requires the gem through Bundler and autoloads the models. Since there is a class named Location, it just assumes you mean the one that has already been loaded :boom:. I'll introduce lazy loading for Rails in a bit (today or tomorrow). You can do the following for the time being.

./Gemfile
```ruby
gem 'azure', require: false
```
./test/test_helper - basically require 'azure' whenever you need to after Location has been loaded.
```ruby
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'

class ActiveSupport::TestCase
  # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
  fixtures :all

  puts Location.inspect
  require 'azure'
  puts Location.inspect
  puts Azure::BaseManagement::Location.inspect

  # Add more helper methods to be used by all tests here...
end

```

**Comment by devigned** [comment]
@mledom did this solve your problem?

**Comment by mledom** [comment]
Yes thanks for the quick response. I forget about that option. 



—
Matthew Ledom
