### ISSUE TITLE
BlobService::call fails when body is an IO

### ISSUE THREAD

**Issue by zachproffitt** [Azure/azure-sdk-for-ruby#272]
Both the body.encoding and body.force_encoding in BlobService::call fail when body is an IO.

```ruby
      def call(method, uri, body=nil, headers=nil)
        # Force the request.body to the content encoding of specified in the header
        # (content encoding probably shouldn't be used this way)
        if headers && !body.nil?
          if headers['Content-Encoding'].nil?
            headers['Content-Encoding'] = body.encoding.to_s
          else
            body.force_encoding(headers['Content-Encoding'])
          end
        end
```

Am I missing something?  Want me to fix?

**Comment by devigned** [comment]
Thank you for the heads up. 

If you want to submit a pull request, I'll make sure it gets reviewed and pulled in.

**Comment by slumos** [comment]
Sorry to say, this entire method is bogus because that's not what Content-Encoding is for. This header is primarily used for compression, and character encoding, which belongs in the Content-Type header, is invalid here.

You can see the complete list of valid values for Content-Encoding [at the IANA registry](https://www.iana.org/assignments/http-parameters/http-parameters.xhtml).

**Comment by devigned** [comment]
@slumos I agree, thus `# (content encoding probably shouldn't be used this way)`. I'll be sure to pass the feedback onto the Storage team.
