### ISSUE TITLE
No docs, no examples, no specs

### ISSUE THREAD

**Issue by idrozd** [Azure/azure-sdk-for-ruby#2774]
No docs, no examples, no specs, googling gives nothing

How do I use PowerBI embed functionality? )

**Comment by nickzhums** [comment]
@idrozd  could you please give more specific details ?

**Comment by idrozd** [comment]
Thanks for response! =)

So I'm using Python example embed app as a prototype for my ruby solution.

I've managed to get the auth token.

Next part is I need to pass it to some endpoint that will respond with embed details:

embedparams from [this python solution](https://github.com/microsoft/PowerBI-Developer-Samples/blob/master/Python/App%20Owns%20Data/powerbiembedding/pbiemjbedservice.py)

The url it builds looks like this:
 reporturl = 'https://api.powerbi.com/v1.0/myorg/groups/' + app.config['WORKSPACE_ID'] + '/reports/' + app.config['REPORT_ID']

So I have workspace and report ids on hand.
I guess I will figure the "myorg" part – is this something I can fetch on report's page?
Will also ask PBI admins.

But when I tried using this API endpoint above, it timed out.
No errors.
So my question is – does this Python example still works with current state of Power BI?
Is this API still operating I mean?
        
Then Javascript  – got this covered already also. I hope ) Example integration worked, so that's good.

**Comment by allenjzhang** [comment]
@idrozd , thanks for your question. PBI's REST specification is [here](https://docs.microsoft.com/en-us/rest/api/power-bi/). The report GET is specifically [here](https://docs.microsoft.com/en-us/rest/api/power-bi/reports/getreportingroup). 

On the GET doc page, you can try out the call using a credential. Looks like the `myorg/groups` should be as it is. Only variables are `GroupId` and `ReportId` which you are adding. You should verify that the `GroupID` and `ReportID` is correct and can get back a value to rule out data issue. If that works, you probably need to look into the auth token because the API relies on the auth token to locate the default tenant.

**Comment by idrozd** [comment]
Thanks again!

Who can I speak to regarding api timing out?

It looks like connection is getting open but nothing happens after.
I assume it should have responded with error code instead of halting if it worked?

❯ curl http://api.powerbi.com:443/v1.0/myorg/groups/ebf08fdb-cadd-423e-9943-6272e5daaf6d/reports/6335e2e9-62c3-4cac-a183-6879b3baf7f9 --verbose
*   Trying 20.40.141.242...
* TCP_NODELAY set
* Connected to api.powerbi.com (20.40.141.242) port 443 (#0)
> GET /v1.0/myorg/groups/ebf08fdb-cadd-423e-9943-6272e5daaf6d/reports/6335e2e9-62c3-4cac-a183-6879b3baf7f9 HTTP/1.1
> Host: api.powerbi.com:443
> User-Agent: curl/7.54.0
> Accept: */*
>

**Comment by lilyjma** [comment]
Closing the issue as it appears to be resolve. Please feel free to open a new one if needed.
