### ISSUE TITLE
Retrieve public IP address for machine

### ISSUE THREAD

**Issue by garethr** [Azure/azure-sdk-for-ruby#279]
I've got the Resource Manager clients setup and making requests against the API, but am failing to find some of the information I'm after. Lets start with the public IP address.

``` ruby
arm_compute_client = ::Azure::ARM::Compute::ComputeManagementClient.new(arm_credentials)
machines = arm_compute_client.virtual_machines.list_all.value!.body.value
machine.first
```

This does output information about the machine (so I can extract the OS, the size, location, name, etc.)

``` ruby
<Azure::ARM::Compute::Models::VirtualMachine:0x007fb7ab992dd8
 @id="/subscriptions/redacted/resourceGroups/name/providers/Microsoft.Compute/virtualMachines/name",
 @location="eastus",
 @name="name",
 @plan=nil,
 @properties=
```

From having the machine, how can I retrieve the public IP address? I'm also looking for the hostname if possible which was available in the ASM API.

If there is somewhere better to ask questions like this let me know.

Some additional examples would be great for problems like this. Once I get everything working I might be able to contribute some common Hello World style ones.

**Comment by devigned** [comment]
In the properties, you should see a networkProfile key:
```json
"networkProfile": {  
      "networkInterfaces": [ {  
        "id":"/subscriptions/{subscription-id}/resourceGroups/myresourceGroup1/providers /Microsoft.Network/networkInterfaces/mynic1"
      } ]
    }
```
You should grab the network interface from above, parse the resource group and the resource name (mynic1), and then call: https://github.com/Azure/azure-sdk-for-ruby/blob/master/resource_management/azure_mgmt_network/lib/azure_mgmt_network/network_interfaces.rb#L136 to get the list of public address resource ids (see: https://msdn.microsoft.com/en-us/library/azure/mt163611.aspx).

From there, you should call https://github.com/Azure/azure-sdk-for-ruby/blob/master/resource_management/azure_mgmt_network/lib/azure_mgmt_network/public_ip_addresses.rb#L136 with the same process as above to finally get the public address resource (see: https://msdn.microsoft.com/en-us/library/azure/mt163570.aspx).

Hmm... I just got a headache trying to walk through this. We need to improve this experience.

I think we will do the following:
- create generic resource get methods which will take ids rather than group_name, resource_name
- create a way to follow(path.to.id) in a resource and perhaps chain the promises together
- make this much less of a pain...

**Comment by garethr** [comment]
@devigned thanks. That's sort of what I'd started inferring but wanted to check I wasn't missing any helpers. Your suggestions are exactly what I had in mind. Happy to provide feedback on any implementation.

Let me know if this is a useful conduit for usage questions like this (ie. fiing GitHub issues) and I'll add others as they come up.

**Comment by devigned** [comment]
@garethr yes, I think this would be a fine conduit for usage questions and feedback. If you are experiencing them then other are as well, and will likely find these discussions useful in the future.

The interesting part of implementation, is that all of the code is generated via https://github.com/azure/autorest using swagger specs in https://github.com/azure/azure-rest-api-specs. The ms-rest-azure gem also lives here: https://github.com/Azure/autorest/tree/dev/ClientRuntimes/Ruby/ms-rest-azure. I imagine some of the helpers will live in ms-rest-azure gem, but other code improvements would live in the template used to generate libraries themselves here: https://github.com/Azure/autorest/tree/dev/AutoRest/Generators/Ruby/Azure.Ruby.

**Comment by devigned** [comment]
@garethr On second thought, I think you should use get_async_common(url, custom_headers) on the client instance with the uri to the networkInterfaces from the VM as the url. This method should get you the networkInterface.

Not saying we shouldn't make it easier, but that will at least give you a way to traverse for the time being.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
