### ISSUE TITLE
Dependency problem with faraday ~> 1.0.0 with azure ~> 0.7 

### ISSUE THREAD

**Issue by AkshayGoyal022** [Azure/azure-sdk-for-ruby#2840]
Hello,

We are trying to upgrade the elasticsearch gem to v7.6.0 which depends on Faraday ~> 1.0.0

The latest version of `azure` is `0.7.10` which has a dependency on Faraday ~> 0.9. We aren't able to upgrade elasticsearch because of this dependency.

Could you please review and try to fix this issue?

Thanks in advance!

**Comment by archerzz** [comment]
Hi @AkshayGoyal022 The Ruby SDK has entered the retirement phase, as announce [here](https://github.com/Azure/azure-sdk-for-ruby#important-announcement). We would not make any substantial changes except for critical security fixes.

Unfortunately Faraday has [break changes](https://github.com/Azure/azure-sdk-for-ruby#important-announcement) since `1.0.0`. So I regret to tell you that we would not update the dependency to `~>`. I hope you could understand our decision. Thanks.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
