### ISSUE TITLE
TableService#query_entities with sorting

### ISSUE THREAD

**Issue by gneiss01** [Azure/azure-sdk-for-ruby#305]
Is it possible to sort results when retrieving entities from table storage?

Given that I have more than 1k records and I only wanted to pull first 10 records with the given sort criteria. How can I achieve it?

**Comment by devigned** [comment]
Sorry for the delay. Is this still an open question?

**Comment by gneiss01** [comment]
Yes unless the sdk is supporting it.

**Comment by devigned** [comment]
> # Sorting data in in the Table service

>The Table service returns entities sorted in ascending order based on PartitionKey and then by RowKey. These keys are string values and to ensure that numeric values sort correctly, you should convert them to a fixed length and pad them with zeroes. For example, if the employee id value you use as the RowKey is an integer value, you should convert employee id 123 to 00000123.

>Many applications have requirements to use data sorted in different orders: for example, sorting employees by name, or by joining date. The following patterns in the section Table Design Patterns address how to alternate sort orders for your entities:

>Intra-partition secondary index pattern - Store multiple copies of each entity using different RowKey values (in the same partition) to enable fast and efficient lookups and alternate sort orders by using different RowKey values.

>Inter-partition secondary index pattern - Store multiple copies of each entity using different RowKey values in separate partitions in separate tables to enable fast and efficient lookups and alternate sort orders by using different RowKey values.

>Log tail pattern - Retrieve the n entities most recently added to a partition by using a RowKey value that sorts in reverse date and time order.

via: https://azure.microsoft.com/en-us/documentation/articles/storage-table-design-guide/

Basically, sorting support needs to be part of your design using table service. You could narrow the range and do in-memory sorting, decide to take one of the approaches outlined in the design doc, or perhaps, use a service like SQL Azure or DocDB.

I'm going to close the issue here as I don't think it's a problem in the SDK, but rather an unsupported feature of Table Service.
