### ISSUE TITLE
Azure::BaseManagement::Location overrides locally defined Location class

### ISSUE THREAD

**Issue by santopuppy** [Azure/azure-sdk-for-ruby#393]
I have an ActiveRecord Location class defined in my Rails 3.2 application. Because of this I get the following error:

```ruby
location.rb:1:in `<top (required)>': superclass mismatch for class Location (TypeError)
```

In the console when I do the following:
```ruby
::Location
=> Azure::BaseManagement::Location
```
```ruby
ExampleApp::Application::Location
=> Azure::BaseManagement::Location
```

**Comment by devigned** [comment]
@veronicagg or @vishrutshah, I don't thing that requires like [this](https://github.com/Azure/azure-sdk-for-ruby/blob/master/lib/azure/base_management/base_management_service.rb#L17) are needed since we are doing autoloading.

Rails will load gems prior to loading modules, which are loaded lazily. If we run a require when the gem is required, then those classes will load and be resolved before the Rails model classes.

Odd part is that I though this was fixed at one point: https://github.com/Azure/azure-sdk-for-ruby/issues/250.

**Comment by devigned** [comment]
Also, it looks like the old example is still up: https://github.com/mledom/azure_test

**Comment by santopuppy** [comment]
Hi @devigned in my case the gem I was using is loading azure as a dependency. It is currently locked in at version 0.6.4. I will try and use an updated version and report back here

**Comment by santopuppy** [comment]
It would seem that this is already fixed in the latest version. I apologize for duplicating an old issue.

Thanks!
