### ISSUE TITLE
Issue in Ruby version specified in azure-sdk gemspec

### ISSUE THREAD

**Issue by bilal-naeem-confiz** [Azure/azure-sdk-for-ruby#463]
Hi,

The gemspec of Azure SDK mentions that it supports ruby version >=1.9.3. We have e.g. following script that creates a resource group

`require 'azure_mgmt_resources'
rmc = Azure::ARM::Resources::ResourceManagementClient.new(credentials)
rmc.subscription_id = 'xxxxxxxx'
resource_group = Azure::ARM::Resources::Models::ResourceGroup.new
resource_group.location = 'east-us'
rmc.resource_groups.create_or_update('TestRG', resource_group)`

This works for ruby v2.x however, it breaks for ruby v1.9.3. Following is the error

```
../Ruby193/lib/ruby/gems/1.9.1/gems/ms_rest_azure-0.4.0/lib/ms_rest_azure/serialization.rb:34:in 'const_get': wrong constant name Azure::ARM::Resources::Models::ResourceGroup (NameError)
from E:/Software/Ruby193/lib/ruby/gems/1.9.1/gems/ms_rest_azure-0.4.0/lib/ms_rest_azure/serialization.rb:34:in 'get_model'
from E:/Software/Ruby193/lib/ruby/gems/1.9.1/gems/ms_rest-0.4.0/lib/ms_rest/serialization.rb:318:in 'serialize_composite_type'
from E:/Software/Ruby193/lib/ruby/gems/1.9.1/gems/ms_rest-0.4.0/lib/ms_rest/serialization.rb:240:in 'serialize'
from E:/Software/Ruby193/lib/ruby/gems/1.9.1/gems/ms_rest-0.4.0/lib/ms_rest/serialization.rb:30:in 'serialize'
from E:/Software/Ruby193/lib/ruby/gems/1.9.1/gems/azure_mgmt_resources-0.5.0/lib/generated/azure_mgmt_resources/resource_groups.rb:302:in 'create_or_update_async'
from E:/Software/Ruby193/lib/ruby/gems/1.9.1/gems/azure_mgmt_resources-0.5.0/lib/generated/azure_mgmt_resources/resource_groups.rb:253:in 'create_or_update'
from E:/Ruby/test.rb:24:in '<top (required)>'
from -e:1:in 'load'
from -e:1:in '<main>'
```

The `deserialize` method (of the ResourceManagementClient) does not work with ruby version 1.9.3. It calls `get_model` method of ms_rest_azure gem which always fails and throws NameError.

Can we have fix for this issue for ruby v1.9.3?

Regards,

**Comment by vishrutshah** [comment]
@bilal-naeem-confiz Thanks for reporting the issue for Ruby version 1.9.3. 

Looking into the issue seems like for Ruby version 1.9.3 it does not automatically walk the namespace hierarchy & we need to manually walk the namespace hierarchy whenever we use the `Object.cons_get` (Example : in `get_model` #[L34](https://github.com/Azure/autorest/blob/master/src/client/Ruby/ms-rest-azure/lib/ms_rest_azure/serialization.rb#L34)). Although, we recommend using Ruby version 2+ (but constradicts with all our gemspec today) we are in-discussion of whether to support backward unto 1.9.3 but we haven't concluded it yet. 

Please use Ruby version 2+ until we come to conclusion. We appreciate your time and efforts.

**Comment by vishrutshah** [comment]
Hello @bilal-naeem-confiz, 

After reviewing on Azure Management Ruby SDK & other related issues like (https://github.com/fog/fog/issues/3910), we decided to support minimum ruby version to 2.0.0. Related PR to update minimum supported Ruby versions are :

https://github.com/Azure/azure-sdk-for-ruby/pull/480 & https://github.com/Azure/autorest/pull/1463

Feel free to review them if you get a chance. I'd like to close this issue once those PR gets merged. 

Thanks,
Vishrut Shah

**Comment by vishrutshah** [comment]
Closing the issue as PRs are now merged. Thanks!
