### ISSUE TITLE
Can't access ServiceBus queue's dead letter queue

### ISSUE THREAD

**Issue by ole108** [Azure/azure-sdk-for-ruby#475]
I use this code to read from normal and dead letter queues:
```ruby
	def initialize
		signer = Azure::ServiceBus::Auth::SharedAccessSigner.new(Settings.azure.servicebus.sas_key_name, Settings.azure.servicebus.sas_key)

		@servicebus = Azure::ServiceBus::ServiceBusService.new(Settings.azure.servicebus.host, { signer: signer })
	end

	def read_event
		sb_queue = Settings.azure.servicebus.queue

		read_event_from_queue(sb_queue)
	end

	def read_event_from_dlq
		sb_queue = Settings.azure.servicebus.queue
		# This gives a 401 (authorization failure) response:
		dlq_name = "#{sb_queue}/%24DeadLetterQueue"
		# This gives a 400 (bad request) response:
		dlq_name = "#{sb_queue}/$DeadLetterQueue"

		read_event_from_queue(dlq_name)
	end

	def read_event_from_queue(queue_name)
		q = @servicebus.get_queue(queue_name)
		count = q.message_count
		puts("message count: #{count}, requires session: #{q.requires_session}, size in bytes: #{q.size_in_bytes}, dead lettering: #{q.dead_lettering_on_message_expiration}")

		message = nil
		if count > 0
			# message = @servicebus.receive_queue_message(q)
			message = @servicebus.peek_lock_queue_message(q)
			if message != nil
				puts("Got message: #{message.inspect}", "From queue: #{queue_name}")
			else
				puts "message is nil!"
			end
		end

		message
	end
```

It works all fine for the normal queue but won't work at all for the dead letter queue.
The errors I get are documented in the comments.

**Comment by sarangan12** [comment]
The gist of the sample program that you have added is this:

#Assume the name of your queue is testqueue
```
q = @servicebus.get_queue(queue_name) # Normally, this will be "testqueue". For DLQ, this will be "testqueue/$DeadLetterQueue"
message = @servicebus.receive_queue_message(q)
```

In azure, the dead letter queues are not seperate queues. Consider that as a container inside some other queue and cannot be accessed directly. So, you cannot pass "testqueue/$DeadLetterQueue" to the get_queue method. This will cause an error since there is no seperate queue with such a name. All we have is a queue named "testqueue" which has a "Dead Letter Queue" container.  

So, How do we access the Dead Letter Queue? 

The following code will work:

`message = @servicebus.receive_queue_message("<queuename>/$DeadLetterQueue",{ :peek_lock => false })`

In the call to receive queue message, you do not send the queue name. But, you send the queue "path". So, the receive_queue_message call will translate this to https://<servicebusname>.servicebus.windows.net/<queuename>/$DeadLetterQueue/messages/head?timeout=60 and will give you the correct result. In essence, there is no way you could get a dead letter queue object directly as you get the normal queue object.


Please let me know if this works for your case.

**Comment by sarangan12** [comment]
Closing this issue now. If you are still facing any issues, please reopen this.

**Comment by ole108** [comment]
I have a green test running now. So I can confirm it is working fine!
Thanks for the clarification!
