### ISSUE TITLE
VirtualMachine on poweroff/poweron/start has to response. You just get Nil

### ISSUE THREAD

**Issue by jkwon2013** [Azure/azure-sdk-for-ruby#566]
Previous history on the issue from Puppet's Trello bug board:
David Justice: Take a look at this code: https://github.com/Azure/vagrant-azure/blob/v2.0/lib/vagrant-azure/action/read_state.rb

cc:
@gregohardy

**Comment by sarangan12** [comment]
The [Power Off](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-03-30/swagger/compute.json#L1297), [Restart](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-03-30/swagger/compute.json#L1334), [Start](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2016-03-30/swagger/compute.json#L1371) are all long running operations and return nil. 

This seems to be a bug in the code. Because the similar long running operation create does not return nil. On looking into the azure-sdk-for-ruby code, you can find the following:
```
........
........
def start(resource_group_name, vm_name, custom_headers = nil)
  response = start_async(resource_group_name, vm_name, custom_headers).value!
  nil
end
........
........
def create_or_update(resource_group_name, vm_name, parameters, custom_headers = nil)
  response = create_or_update_async(resource_group_name, vm_name, parameters, custom_headers).value!
  response.body unless response.nil?
end
.........
.........
```

As you can see, the nil is intentionally returned and this causes the issue. I will work on the fix and update this issue soon.

**Comment by sarangan12** [comment]
On further analysis, it seems in addition to the specified methods, the following methods are also affected by the same behavior. (Needs verification & confirmation)

1. delete
2. delete_async
3. deallocate
4. deallocate_async
5. generalize
6. power_off	
7. power_off_async
8. restart
9. restart_async
10. start
11. start_async
12. redeploy
13. redeploy_async
14. begin_delete
15. begin_deallocate
16. begin_power_off
17. begin_restart
18. begin_start
19. begin_redeploy

I will verify and confirm the same.

**Comment by sarangan12** [comment]
@gregohardy The issue has been fixed now in the master branch and must be available in the next release.
