### ISSUE TITLE
Issue installing Azure Gem on < 2.1 is broken

### ISSUE THREAD

**Issue by ElvenSpellmaker** [Azure/azure-sdk-for-ruby#637]
The Gem page says that the lowest supported Ruby for version 0.7.1 of the gem is 1.9.3 and this worked until recently (I did an internal PR to upgrade the Ruby version to 2.0 on 29th November).

When it said that 2.0 is needed we switched and now is causing us problems again by saying that 2.1 is needed. As we'd like to tie our infrastructure to a known stable version we don't want to have to keep upgrading Ruby versions all the time, especially when the gem says on the website it requires 1.9.3 minimum.

Every time this breaks it starts breaking puppet profiles we have that require this gem.

![image](https://cloud.githubusercontent.com/assets/2286713/21598247/3a336d4c-d151-11e6-83dc-fcf847a9b041.png)

I'm assuming there is a dependency somewhere that isn't being pinned which is causing this?

**Comment by ElvenSpellmaker** [comment]
The problem seems to be nokogiri related based on this puppet run output:
```
Error: Could not update: Execution of '/usr/local/rvm/bin/rvm ruby-2.0.0-p598 do gem install -v 0.7.1 --no-rdoc --no-ri azure' returned 1: ERROR:  Error installing azure:
        nokogiri requires Ruby version >= 2.1.0.
```

**Comment by ElvenSpellmaker** [comment]
Related is the error I get when I try to install on Ruby 1.9.3:
```
[root@test-vesite-upload jblower]# rvm use 1.9.3 do gem install azure -v 0.7.1
Fetching: public_suffix-2.0.5.gem (100%)
ERROR:  Error installing azure:
        public_suffix requires Ruby version >= 2.0.
```

**Comment by ElvenSpellmaker** [comment]
The last version of Nokogiri to support 1.9.3 was [1.6.8.1](https://rubygems.org/gems/nokogiri/versions/1.6.8.1) it seems.

That still doesn't solve the `public_suffix` which seems to always need 2.0 (but the gem used to work on 1.9.3 before mid-November)

**Comment by vishrutshah** [comment]
@ElvenSpellmaker Thank you very much reporting the issue. 

As you mentioned, Part of the issue is because of `nokogiri` gem which now has minimum requirement changed and another part is we have pessimistic depedency on that package [s.add_runtime_dependency('nokogiri',                '~> 1.6') ](https://github.com/Azure/azure-sdk-for-ruby/blob/asm/azure.gemspec#L39).

We are looking into this on how should we better specify dependency and how should we move forward with the other dependent packages. 

Our options are 

1. we update our dependency on nokogiri gem with ~>1.6.8 so that it can work with Ruby version >=1.9.3
2. Verify the possibility of moving forward with nokogiri support but we need extensive testing from our end of that
3. Move away from the nokogiri dependency. 

Give us some time to understand these options and find the best solution. I'll keep you posted on what we decide. 

Thanks for your patience.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
