### ISSUE TITLE
azure_mgmt_insights needs to be updated to include Events and Event Categories and Metrics and Metric Definitions

### ISSUE THREAD

**Issue by pparamalingam** [Azure/azure-sdk-for-ruby#791]
The azure_mgmt_insights library is missing methods to query Activity Logs, Also to note, the Insights API was renamed to Monitor API.

**Comment by Ilanak** [comment]
Is there an ETA for this bug?

**Comment by veronicagg** [comment]
Is what you're looking for in any of the the following REST API specs: https://github.com/Azure/azure-rest-api-specs/tree/current/specification/monitor/resource-manager/microsoft.insights 
If it's there, then it should be included in the gems. 
If it isn't, can you comment a bit more (maybe a link to the Azure service) on what you're looking to have available?

**Comment by Ilanak** [comment]
I was looking for GetMetric/ [GetMetricFiltered](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/monitor/resource-manager/microsoft.insights/2016-09-01/examples/GetMetricFiltered.json)..
I didn't find it in the gem(https://github.com/Azure/azure-sdk-for-ruby/tree/master/management/azure_mgmt_monitor/lib/generated/azure_mgmt_monitor/models)

**Comment by veronicagg** [comment]
I see, thanks, those operations are part of the spec at https://github.com/Azure/azure-rest-api-specs/blob/2fb9a0b3b902335ff0b0033711c234431931ec9d/specification/monitor/data-plane/microsoft.insights/2016-09-01/metrics_API.json, we're currently shipping gems for "resource-manager" APIs. I don't know yet when we'll be shipping gems for specs under "data-plane" (folder), will let you know if we do.

**Comment by gucalder** [comment]
The Metrics API and the and ActivityLogs (aka Events) API are in the data-plane even though the calls go through ARM. Notice that these APIs can only consume data, i.e. no PUT, UPDATE, DELETE, POST, only GET.

Due to historic reasons these APIs where separated from the other ones classified as resource-manager, but they are all packed and published in the same SDK dll (current public version is Microsoft.Azure.Management.Monitor 0.16.1-preview). However, all these calls go through ARM.

After Ignite I am planning to move these to the resource-manager folder. No concrete ETA at this moment.

**Comment by kurtzeborn** [comment]
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk
